//! Phase 2.4: Self-Play Training — generate synthetic training curriculum
//! targeting weaknesses. The agent generates problems, solves them, and
//! adapts difficulty based on success rate (GRPO-inspired).
//!
//! From AGI_PLAN.md §2.4:
//! 1. Identify weakness (high response time, low confidence, errors)
//! 2. Generate synthetic training examples targeting weakness
//! 3. Fine-tune or adapt to improve
//! 4. Re-test

use serde::{Deserialize, Serialize};

/// Training categories — each tracked independently.
pub const CATEGORIES: &[&str] = &["math", "logic", "coding", "planning"];

/// Stats for a single category.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CategoryStats {
    pub successes: u32,
    pub attempts: u32,
    pub difficulty: u8, // 1-10
}

impl CategoryStats {
    pub fn success_rate(&self) -> f32 {
        if self.attempts == 0 { return 0.5; }
        self.successes as f32 / self.attempts as f32
    }
}

/// A training problem generated by the self-play system.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(dead_code)]
pub struct TrainingProblem {
    pub category: String,
    pub difficulty: u8,
    pub problem: String,
    pub expected_answer: String,
}

/// Result of attempting a training problem.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[allow(dead_code)]
pub struct TrainingResult {
    pub problem: TrainingProblem,
    pub attempt: String,
    pub correct: bool,
    pub reward: f32,
}

/// Self-Play Training Curriculum — manages categories, tracks performance,
/// selects weak areas, adjusts difficulty.
pub struct TrainingCurriculum {
    stats: std::collections::HashMap<String, CategoryStats>,
    total_problems: u32,
    total_correct: u32,
}

impl TrainingCurriculum {
    pub fn new() -> Self {
        let mut stats = std::collections::HashMap::new();
        for cat in CATEGORIES {
            stats.insert(cat.to_string(), CategoryStats {
                successes: 0,
                attempts: 0,
                difficulty: 1,
            });
        }
        TrainingCurriculum {
            stats,
            total_problems: 0,
            total_correct: 0,
        }
    }

    /// Select a category weighted by weakness (lower success rate = higher weight).
    /// Returns (category, difficulty).
    pub fn select_category(&self) -> (String, u8) {
        let weights: Vec<(&str, f32)> = CATEGORIES.iter().map(|&c| {
            let rate = self.stats.get(c).map(|s| s.success_rate()).unwrap_or(0.5);
            // Inverse weighting: weaker categories get higher weight
            let weight = 0.9 - rate + 0.05;
            (c, weight.max(0.05))
        }).collect();

        let total: f32 = weights.iter().map(|(_, w)| w).sum();
        let r = rand_f32() * total;
        let mut cumulative = 0.0;
        for (cat, weight) in &weights {
            cumulative += weight;
            if r <= cumulative {
                let diff = self.stats.get(*cat).map(|s| s.difficulty).unwrap_or(1);
                return (cat.to_string(), diff);
            }
        }
        // Fallback
        ("math".to_string(), 1)
    }

    /// Record a training result and adjust difficulty.
    #[allow(dead_code)]
    pub fn record_result(&mut self, result: &TrainingResult) {
        let cat = &result.problem.category;
        if let Some(stats) = self.stats.get_mut(cat) {
            stats.attempts += 1;
            if result.correct {
                stats.successes += 1;
            }
            self.total_problems += 1;
            if result.correct { self.total_correct += 1; }

            // Adjust difficulty: increase on success, decrease on failure
            let delta: i8 = if result.correct { 1 } else { -1 };
            let new_diff = (stats.difficulty as i8 + delta).max(1).min(10);
            stats.difficulty = new_diff as u8;
        }
    }

    /// Get the overall success rate.
    pub fn overall_rate(&self) -> f32 {
        if self.total_problems == 0 { return 0.0; }
        self.total_correct as f32 / self.total_problems as f32
    }

    /// Get per-category stats.
    pub fn category_stats(&self, category: &str) -> Option<&CategoryStats> {
        self.stats.get(category)
    }

    #[allow(dead_code)]
    pub fn all_stats(&self) -> &std::collections::HashMap<String, CategoryStats> {
        &self.stats
    }

    /// Summary string.
    pub fn summary(&self) -> String {
        let mut parts = Vec::new();
        for cat in CATEGORIES {
            if let Some(s) = self.stats.get(*cat) {
                parts.push(format!("{}: {:.0}% (d={}, {}/{}",
                    cat,
                    s.success_rate() * 100.0,
                    s.difficulty,
                    s.successes,
                    s.attempts,
                ));
            }
        }
        format!("overall {:.0}% ({}/{} problems) | {}",
            self.overall_rate() * 100.0,
            self.total_correct,
            self.total_problems,
            parts.join(", "),
        )
    }
}

impl Default for TrainingCurriculum {
    fn default() -> Self {
        Self::new()
    }
}

/// Generate synthetic training problems for a given category and difficulty.
/// Returns a list of problem/answer pairs for self-play.
pub fn generate_problems(category: &str, difficulty: u8, count: usize) -> Vec<TrainingProblem> {
    let mut rng = rand::thread_rng();
    let mut problems = Vec::with_capacity(count);

    for _ in 0..count {
        let (problem, answer) = match category {
            "math" => generate_math_problem(difficulty, &mut rng),
            "logic" => generate_logic_problem(difficulty, &mut rng),
            "coding" => generate_coding_problem(difficulty, &mut rng),
            "planning" => generate_planning_problem(difficulty, &mut rng),
            _ => ("unknown".to_string(), "unknown".to_string()),
        };
        problems.push(TrainingProblem {
            category: category.to_string(),
            difficulty,
            problem,
            expected_answer: answer,
        });
    }
    problems
}

fn generate_math_problem(difficulty: u8, rng: &mut impl rand::Rng) -> (String, String) {
    match difficulty {
        1..=3 => {
            // Simple arithmetic
            let a = rng.gen_range(1..=20);
            let b = rng.gen_range(1..=20);
            let op = if rng.gen_bool(0.5) { "+" } else { "-" };
            let answer = if op == "+" { a + b } else { a.max(b) - a.min(b) };
            (format!("{a} {op} {b} = ?"), answer.to_string())
        }
        4..=6 => {
            // Multiplication / division
            let a = rng.gen_range(2..=12);
            let b = rng.gen_range(2..=12);
            let answer = a * b;
            (format!("{a} × {b} = ?"), answer.to_string())
        }
        _ => {
            // Word problems
            let a = rng.gen_range(10..=100);
            let b = rng.gen_range(5..=20);
            let answer = a * b;
            (format!("If each box holds {b} items and you have {a} boxes, how many items total?"), answer.to_string())
        }
    }
}

fn generate_logic_problem(difficulty: u8, rng: &mut impl rand::Rng) -> (String, String) {
    match difficulty {
        1..=3 => {
            // Simple boolean
            let a = rng.gen_bool(0.5);
            let b = rng.gen_bool(0.5);
            let answer = a && b;
            (format!("True AND False = ? (true/false)"), if answer { "true" } else { "false" }.to_string())
        }
        4..=6 => {
            // De Morgan
            let val = if rng.gen_bool(0.5) { "True" } else { "False" };
            let not_val = if val == "True" { "False" } else { "True" };
            (format!("NOT ({val}) = ?"), not_val.to_string())
        }
        _ => {
            // Syllogism
            if rng.gen_bool(0.5) {
                ("All men are mortal. Socrates is a man. Is Socrates mortal?".to_string(), "yes".to_string())
            } else {
                ("If A implies B, and B implies C, does A imply C?".to_string(), "yes".to_string())
            }
        }
    }
}

fn generate_coding_problem(difficulty: u8, rng: &mut impl rand::Rng) -> (String, String) {
    match difficulty {
        1..=3 => {
            let vals: Vec<i32> = (0..3).map(|_| rng.gen_range(1..=10)).collect();
            let max = vals.iter().max().unwrap();
            (format!("What is max({:?})?", vals), max.to_string())
        }
        4..=6 => {
            let vals: Vec<i32> = (0..5).map(|_| rng.gen_range(1..=20)).collect();
            let sum: i32 = vals.iter().sum();
            (format!("What is the sum of {:?}?", vals), sum.to_string())
        }
        _ => {
            let base: i32 = rng.gen_range(2..=10);
            let exp = 2u32;
            let answer = base.pow(exp);
            (format!("Implement a function that computes {base}^{exp} and return the result (just the number)."), answer.to_string())
        }
    }
}

fn generate_planning_problem(difficulty: u8, rng: &mut impl rand::Rng) -> (String, String) {
    match difficulty {
        1..=3 => {
            let a = rng.gen_range(3..=10);
            let b = rng.gen_range(1..=5);
            let answer = a * b;
            (format!("You have {a} tasks, each taking {b} minutes. Total minutes needed?"), answer.to_string())
        }
        4..=6 => {
            let total = rng.gen_range(20..=100);
            let per_day = rng.gen_range(5..=20);
            let days = (total as f32 / per_day as f32).ceil() as u32;
            (format!("Need to process {total} items. Capacity: {per_day}/day. Minimum days?"), days.to_string())
        }
        _ => {
            let n = rng.gen_range(5..=10);
            let m = n * (n - 1) / 2;
            (format!("How many connections needed to fully connect {n} nodes? (complete graph)"), m.to_string())
        }
    }
}

/// Simple pseudo-random f32 in [0, 1) — deterministic for testing, random for real.
fn rand_f32() -> f32 {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    let mut hasher = DefaultHasher::new();
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos()
        .hash(&mut hasher);
    (hasher.finish() % 10000) as f32 / 10000.0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_curriculum_initialization() {
        let curr = TrainingCurriculum::new();
        assert_eq!(curr.overall_rate(), 0.0);
        assert!(curr.summary().contains("math"));
    }

    #[test]
    fn test_select_category_returns_valid() {
        let curr = TrainingCurriculum::new();
        let (cat, diff) = curr.select_category();
        assert!(CATEGORIES.contains(&cat.as_str()));
        assert!(diff >= 1 && diff <= 10);
    }

    #[test]
    fn test_record_correct_increases_success() {
        let mut curr = TrainingCurriculum::new();
        let problem = TrainingProblem {
            category: "math".to_string(),
            difficulty: 3,
            problem: "2+2".to_string(),
            expected_answer: "4".to_string(),
        };
        let result = TrainingResult {
            problem,
            attempt: "4".to_string(),
            correct: true,
            reward: 1.0,
        };
        curr.record_result(&result);
        let stats = curr.category_stats("math").unwrap();
        assert_eq!(stats.successes, 1);
        assert_eq!(stats.attempts, 1);
        assert_eq!(stats.difficulty, 2); // 1 + 1 = 2
    }

    #[test]
    fn test_record_incorrect_increases_attempts() {
        let mut curr = TrainingCurriculum::new();
        let problem = TrainingProblem {
            category: "logic".to_string(),
            difficulty: 3,
            problem: "p AND NOT p".to_string(),
            expected_answer: "false".to_string(),
        };
        let result = TrainingResult {
            problem,
            attempt: "true".to_string(),
            correct: false,
            reward: 0.0,
        };
        curr.record_result(&result);
        let stats = curr.category_stats("logic").unwrap();
        assert_eq!(stats.successes, 0);
        assert_eq!(stats.attempts, 1);
        // Internal difficulty starts at 1, failure tries to go to 0, clamped at 1
        assert_eq!(stats.difficulty, 1);
    }

    #[test]
    fn test_difficulty_bounds() {
        let mut curr = TrainingCurriculum::new();
        // Push math difficulty to 1, then fail
        let problem = TrainingProblem {
            category: "math".to_string(),
            difficulty: 1,
            problem: "test".to_string(),
            expected_answer: "x".to_string(),
        };
        let result = TrainingResult {
            problem, attempt: "wrong".to_string(), correct: false, reward: 0.0,
        };
        curr.record_result(&result);
        assert_eq!(curr.category_stats("math").unwrap().difficulty, 1); // Clamped at 1
    }

    #[test]
    fn test_weakness_weighting() {
        // After many failures in "math", it should be selected more often
        let mut curr = TrainingCurriculum::new();
        for _ in 0..20 {
            let problem = TrainingProblem {
                category: "math".to_string(),
                difficulty: 5,
                problem: "hard".to_string(),
                expected_answer: "impossible".to_string(),
            };
            let result = TrainingResult {
                problem, attempt: "wrong".to_string(), correct: false, reward: 0.0,
            };
            curr.record_result(&result);
        }

        // Now select should prefer math (weak)
        let mut math_count = 0;
        for _ in 0..100 {
            let (cat, _) = curr.select_category();
            if cat == "math" { math_count += 1; }
        }
        // With 20 failures in math and 0 in others, math should be selected > 25% of the time
        assert!(math_count > 25, "math was selected {} out of 100 times", math_count);
    }

    #[test]
    fn test_overall_rate() {
        let mut curr = TrainingCurriculum::new();
        for i in 0..10 {
            let problem = TrainingProblem {
                category: "coding".to_string(),
                difficulty: 5,
                problem: "test".to_string(),
                expected_answer: "x".to_string(),
            };
            let result = TrainingResult {
                problem,
                attempt: "x".to_string(),
                correct: i < 7, // 7 correct out of 10
                reward: if i < 7 { 1.0 } else { 0.0 },
            };
            curr.record_result(&result);
        }
        assert!((curr.overall_rate() - 0.7).abs() < 0.01);
    }
}
